### ISSUE TITLE
Settings panel bug when Multiple Zoom windows are open

### ISSUE THREAD

**Issue by fisher729** [mohammad-suliman/zoom-enhancements#3]
Steps to Reproduce:

1. Launch Zoom.
2. Go to the settings screen.
3. Open the settings panel
4. Scroll to the bottom

Expected: Only one item called Zoom Enhancements Settings should be in the settings panel.
Actual: Two items called Zoom Enhancements Settings can be found in the settings panel.

Using NVDA 2020.4 with add-on version 1.1.

**Comment by mohammad-suliman** [comment]
@fisher729  thanks for your report! The issue will be fixed in the next version.

**Comment by fisher729** [comment]
Hi. I'm curious to know how you'll fix it. Perhaps a 1.2 version to
take care of this specific issue, then focus on other issues for a 1.3
release?
